### ISSUE TITLE
Glossary - officially introduce the "Mobility" entity

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-wp3-technical-glossary#1]
@erasmus-without-paper/all-members 

In the current glossary draft WP3 proposes to introduce a "Person Mobility" entity defined as:

> Generalization of a person (student or employee) who is a candidate for mobility between HEIs.

However, this definition seems a bit wrong, for a number of reasons:
1. The "entity-entity" naming scheme is usually used for unnamed many-to-many relationships in ERDs. "Student Mobility" name seems to imply that there _can_ be a mobility _without_ a person, or with many. Whereas, in our model, a single mobility is always related to a single person, so we have a one-to-many relationship here.
2. The definition does not match the usage proposed in the data schema uploaded by WP3 [here](https://github.com/erasmus-without-paper/ewp-specs-api-mobilities/blob/eafa66b4d3cae2b98532c5aaa3db35493a6b1a7f/response_new.xsd#L5). In this XSD the "person-mobility" element describes the mobility, not the person (and the person is only one of the properties of the mobility).

We propose the following changes:
- Rename the `<person-mobility>` element to `<mobility>`.
- Introduce the "Mobility" entity into the technical glossary (with a definition more in line with the definition of the [Outgoing Mobility object](https://github.com/erasmus-without-paper/ewp-specs-mobility-flowcharts/tree/ab08362215dd35e0edf7b6b5f3910faaf34a70c4#outgoing-mobility-object)).

**Comment by wrygiel** [comment]
Does anyone have any other suggestions? @erasmus-without-paper/all-members?

Names proposed so far:
1. `<mobility>` (by @erasmus-without-paper/wp4)
2. `<person-mobility>` (by @erasmus-without-paper/wp3)

Since @erasmus-without-paper/wp3 is responsible for designing the internal schemas, I guess we will go with `<person-mobility>` unless we can persuade each other ;)

**Comment by kaiqu** [comment]
I haven't had the time to follow the various discussions, but I will try to catch up...

Principally, there is nothing wrong with having names with multiple parts (separated by spaces, hyphens, underscores or whatever) for explicit entities (not just materializations of many-to-many relationships). Also, Person Mobility does have a many-to-one relationship with Person in the model.

On the other hand, I don't mind greatly to change the name to Mobility as suggested :-)
