### ISSUE TITLE
Glossary -"Academic Term" instead of "Term"?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-wp3-technical-glossary#2]
The current glossary introduces a term "Term". However, it seems to me that the "term" term is too vague of a term. Wouldn't it be safer if we referred to academic terms as "Academic Terms"?

@erasmus-without-paper/all-members - Which of the two would you rather see in XML files - `<term>` or `<academic-term>`? Once we choose one name, we should be able to use it in all contexts.

**Comment by mikesteez** [comment]
Academic term is much more precise, and I would like to see that used.

**Comment by kaiqu** [comment]
I reached the same conclusion - it is called Academic Term in the data model, and the same name (academic-term) will be used in the format.
