### ISSUE TITLE
Glossary - "Parner" vs. "EWP Partner" vs. "IIA Partner"

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-wp3-technical-glossary#3]
The current WP3's glossary proposal defines "Partner" as:

> A HEI taking part in an IIA.

However, in many existing documents the word "partner" has already gained some different meanings. I think that the term "IIA Partner" would be a better fit for the above definition.

@erasmus-without-paper/all-members

**Comment by kaiqu** [comment]
Yes, it's called IIA Partner in the current version of the model.
