### ISSUE TITLE
Glossary - "Owner Unit" or "Parent Unit"?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-wp3-technical-glossary#4]
@erasmus-without-paper/all-members 

Quote from WP3's proposal:

> Owner Unit - Pointer in Organization Unit to the Organization Unit immediately above in the hierarchy.

I believe we are describing a tree here. Perhaps it would be safer to name this a "Parent Unit" then, as a "parent node" in a tree? I'm not sure if "owner" would be proper in all contexts.

**Comment by mikesteez** [comment]
Parent Unit would be appropriate - but do we really need to model a tree? Is this a real necessity?

**Comment by wrygiel** [comment]
In our (WP4's) proposal there was no tree (we have a flat Departments API, with no subunits), in WP3's proposal there is. I'm not yet sure if exposing a full tree is necessary.

**Comment by geirmv** [comment]
Exchanging the relations between organization units is probably not useful for the receiving institution, but I recommend we keep the relation in the data model.

**Comment by wrygiel** [comment]
It cannot hurt, I guess. Especially if `<parent-unit-id>` would be optional. However, we would need to rename "Departments API" to "Organizational Units API" in such case.

**Comment by kaiqu** [comment]
I think it's a good idea to keep the Institution and Organization Unit/Department formats separate.
Also I have no problem with keeping the parent-unit-id in the data model only, at least for the moment (it's easy to add later, if needed). This means that underlying Organization Units (Departments) will be presented as lying "flatly" under the Institution.

**Comment by wrygiel** [comment]
[`<parent-ounit-id>`](https://github.com/erasmus-without-paper/ewp-specs-api-ounits/blob/v0.2.0/response.xsd#L96) is already present in the latest draft.

Also, implementers may choose between specifying their units structure as a tree, or as a flat list.
